export const categories = [
  {
    id: "cat_1",
    parent_id: null,
    slug: "electronics",
    name: "Electronics",
    description: "All kinds of electronics",
    products: 20,
    created: Date.now(),
    updated: Date.now(),
    assets: [],
  },
  {
    id: "cat_2",
    parent_id: null,
    slug: "clothing",
    name: "Clothing",
    description: "All clothing items",
    products: 20,
    created: Date.now(),
    updated: Date.now(),
    assets: [],
  },
  {
    id: "cat_3",
    parent_id: null,
    slug: "mens-fashion",
    name: "Men's Fashion",
    description: "Men's fashion and accessories",
    products: 15,
    created: Date.now(),
    updated: Date.now(),
    assets: [],
  },
  {
    id: "cat_4",
    parent_id: null,
    slug: "womens-fashion",
    name: "Women's Fashion",
    description: "Women's fashion and accessories",
    products: 15,
    created: Date.now(),
    updated: Date.now(),
    assets: [],
  },
  {
    id: "cat_5",
    parent_id: null,
    slug: "health",
    name: "Health",
    description: "Health products and equipment",
    products: 10,
    created: Date.now(),
    updated: Date.now(),
    assets: [],
  },
  {
    id: "cat_6",
    parent_id: null,
    slug: "tools",
    name: "Tools",
    description: "Various tools and equipment",
    products: 10,
    created: Date.now(),
    updated: Date.now(),
    assets: [],
  },
];

export const products = [
  // Electronics
  {
    id: "prod_1",
    product_id: "prod_1",
    name: "Samsung Galaxy S21",
    product_name: "Samsung Galaxy S21",
    sku: "SAMS21",
    permalink: "samsung-galaxy-s21",
    quantity: 50,
    price: {
      raw: 799,
      formatted: "799.00",
      formatted_with_symbol: "$799.00",
      formatted_with_code: "799.00 USD",
    },
    line_total: {
      raw: 799,
      formatted: "799.00",
      formatted_with_symbol: "$799.00",
      formatted_with_code: "799.00 USD",
    },
    is_valid: true,
    product_meta: [],
    selected_options: [],
    variant: {
      id: "var_1",
      sku: "SAMS21_BLACK",
      description: "Samsung Galaxy S21 - Black",
      inventory: 30,
      price: {
        raw: 799,
        formatted: "799.00",
        formatted_with_symbol: "$799.00",
        formatted_with_code: "799.00 USD",
      },
      is_valid: true,
    },
    image: {
      type: "image",
      source: "https://example.com/products/samsung_galaxy_s21.jpg",
      asset_id: "asset_1",
    },
    category_id: "cat_1",
  },
  {
    id: "prod_2",
    product_id: "prod_2",
    name: "Sony WH-1000XM4 Headphones",
    product_name: "Sony WH-1000XM4 Headphones",
    sku: "SONY1000XM4",
    permalink: "sony-wh-1000xm4-headphones",
    quantity: 75,
    price: {
      raw: 349,
      formatted: "349.00",
      formatted_with_symbol: "$349.00",
      formatted_with_code: "349.00 USD",
    },
    line_total: {
      raw: 349,
      formatted: "349.00",
      formatted_with_symbol: "$349.00",
      formatted_with_code: "349.00 USD",
    },
    is_valid: true,
    product_meta: [],
    selected_options: [],
    variant: {
      id: "var_2",
      sku: "SONY1000XM4_SILVER",
      description: "Sony WH-1000XM4 - Silver",
      inventory: 40,
      price: {
        raw: 349,
        formatted: "349.00",
        formatted_with_symbol: "$349.00",
        formatted_with_code: "349.00 USD",
      },
      is_valid: true,
    },
    image: {
      type: "image",
      source: "https://example.com/products/sony_wh1000xm4.jpg",
      asset_id: "asset_2",
    },
    category_id: "cat_1",
  },
  {
    id: "prod_3",
    product_id: "prod_3",
    name: "Apple MacBook Air M1",
    product_name: "Apple MacBook Air M1",
    sku: "MACAIR_M1",
    permalink: "apple-macbook-air-m1",
    quantity: 20,
    price: {
      raw: 999,
      formatted: "999.00",
      formatted_with_symbol: "$999.00",
      formatted_with_code: "999.00 USD",
    },
    line_total: {
      raw: 999,
      formatted: "999.00",
      formatted_with_symbol: "$999.00",
      formatted_with_code: "999.00 USD",
    },
    is_valid: true,
    product_meta: [],
    selected_options: [],
    variant: {
      id: "var_3",
      sku: "MACAIR_M1_SILVER",
      description: "Apple MacBook Air M1 - Silver",
      inventory: 10,
      price: {
        raw: 999,
        formatted: "999.00",
        formatted_with_symbol: "$999.00",
        formatted_with_code: "999.00 USD",
      },
      is_valid: true,
    },
    image: {
      type: "image",
      source: "https://example.com/products/macbook_air_m1.jpg",
      asset_id: "asset_3",
    },
    category_id: "cat_1",
  },
  {
    id: "prod_4",
    product_id: "prod_4",
    name: "Nike Air Max 270",
    product_name: "Nike Air Max 270",
    sku: "NIKEAIR270",
    permalink: "nike-air-max-270",
    quantity: 80,
    price: {
      raw: 150,
      formatted: "150.00",
      formatted_with_symbol: "$150.00",
      formatted_with_code: "150.00 USD",
    },
    line_total: {
      raw: 150,
      formatted: "150.00",
      formatted_with_symbol: "$150.00",
      formatted_with_code: "150.00 USD",
    },
    is_valid: true,
    product_meta: [],
    selected_options: [],
    variant: {
      id: "var_4",
      sku: "NIKEAIR270_BLACK",
      description: "Nike Air Max 270 - Black",
      inventory: 50,
      price: {
        raw: 150,
        formatted: "150.00",
        formatted_with_symbol: "$150.00",
        formatted_with_code: "150.00 USD",
      },
      is_valid: true,
    },
    image: {
      type: "image",
      source: "https://example.com/products/nike_air_max_270.jpg",
      asset_id: "asset_4",
    },
    category_id: "cat_2",
  },
  {
    id: "prod_5",
    product_id: "prod_5",
    name: 'Apple iPad Pro 11"',
    product_name: 'Apple iPad Pro 11"',
    sku: "IPADPRO11",
    permalink: "apple-ipad-pro-11",
    quantity: 35,
    price: {
      raw: 799,
      formatted: "799.00",
      formatted_with_symbol: "$799.00",
      formatted_with_code: "799.00 USD",
    },
    line_total: {
      raw: 799,
      formatted: "799.00",
      formatted_with_symbol: "$799.00",
      formatted_with_code: "799.00 USD",
    },
    is_valid: true,
    product_meta: [],
    selected_options: [],
    variant: {
      id: "var_5",
      sku: "IPADPRO11_SILVER",
      description: 'Apple iPad Pro 11" - Silver',
      inventory: 25,
      brand: "Apple",
      color: "Black",
      price: {
        raw: 799,
        formatted: "799.00",
        formatted_with_symbol: "$799.00",
        formatted_with_code: "799.00 USD",
      },
      is_valid: true,
    },
    image: {
      type: "image",
      source: "https://example.com/products/ipad_pro_11.jpg",
      asset_id: "asset_5",
    },
    category_id: "cat_1",
  },
  {
    id: "prod_6",
    product_id: "prod_6",
    name: "Sony PlayStation 5",
    product_name: "Sony PlayStation 5",
    sku: "PS5",
    permalink: "sony-playstation-5",
    quantity: 60,
    price: {
      raw: 499,
      formatted: "499.00",
      formatted_with_symbol: "$499.00",
      formatted_with_code: "499.00 USD",
    },
    line_total: {
      raw: 499,
      formatted: "499.00",
      formatted_with_symbol: "$499.00",
      formatted_with_code: "499.00 USD",
    },
    is_valid: true,
    product_meta: [],
    selected_options: [],
    variant: {
      id: "var_6",
      sku: "PS5_WHITE",
      description: "Sony PlayStation 5 - White",
      inventory: 50,
      price: {
        raw: 499,
        formatted: "499.00",
        formatted_with_symbol: "$499.00",
        formatted_with_code: "499.00 USD",
      },
      is_valid: true,
    },
    image: {
      type: "image",
      source: "https://example.com/products/playstation_5.jpg",
      asset_id: "asset_6",
    },
    category_id: "cat_1",
  },
  {
    id: "prod_7",
    product_id: "prod_7",
    name: "Bose SoundLink Bluetooth Speaker",
    product_name: "Bose SoundLink Bluetooth Speaker",
    sku: "BOSELINK",
    permalink: "bose-soundlink-bluetooth-speaker",
    quantity: 100,
    price: {
      raw: 199,
      formatted: "199.00",
      formatted_with_symbol: "$199.00",
      formatted_with_code: "199.00 USD",
    },
    line_total: {
      raw: 199,
      formatted: "199.00",
      formatted_with_symbol: "$199.00",
      formatted_with_code: "199.00 USD",
    },
    is_valid: true,
    product_meta: [],
    selected_options: [],
    variant: {
      id: "var_7",
      sku: "BOSELINK_BLACK",
      description: "Bose SoundLink - Black",
      inventory: 80,
      brand: "Bose",
      color: "white",
      price: {
        raw: 199,
        formatted: "199.00",
        formatted_with_symbol: "$199.00",
        formatted_with_code: "199.00 USD",
      },
      is_valid: true,
    },
    image: {
      type: "image",
      source: "https://example.com/products/bose_soundlink.jpg",
      asset_id: "asset_7",
    },
    category_id: "cat_1",
  },
  {
    id: "prod_8",
    product_id: "prod_8",
    name: "GoPro Hero9 Black",
    product_name: "GoPro Hero9 Black",
    sku: "GOPROH9",
    permalink: "gopro-hero9-black",
    quantity: 40,
    price: {
      raw: 399,
      formatted: "399.00",
      formatted_with_symbol: "$399.00",
      formatted_with_code: "399.00 USD",
    },
    line_total: {
      raw: 399,
      formatted: "399.00",
      formatted_with_symbol: "$399.00",
      formatted_with_code: "399.00 USD",
    },
    is_valid: true,
    product_meta: [],
    selected_options: [],
    variant: {
      id: "var_8",
      sku: "GOPROH9_BLACK",

      description: "GoPro Hero9 Black",
      inventory: 35,
      brand: "GoPro",
      color: "Black",
      price: {
        raw: 399,
        formatted: "399.00",
        formatted_with_symbol: "$399.00",
        formatted_with_code: "399.00 USD",
      },
      is_valid: true,
    },
    image: {
      type: "image",
      source: "https://example.com/products/gopro_hero9.jpg",
      asset_id: "asset_8",
    },
    category_id: "cat_1",
  },
  {
    id: "prod_9",
    product_id: "prod_9",
    name: "JBL Charge 4 Portable Speaker",
    product_name: "JBL Charge 4 Portable Speaker",
    sku: "JBLCHARGE4",
    permalink: "jbl-charge-4-portable-speaker",
    quantity: 90,
    price: {
      raw: 179,
      formatted: "179.00",
      formatted_with_symbol: "$179.00",
      formatted_with_code: "179.00 USD",
    },
    line_total: {
      raw: 179,
      formatted: "179.00",
      formatted_with_symbol: "$179.00",
      formatted_with_code: "179.00 USD",
    },
    is_valid: true,
    product_meta: [],
    selected_options: [],
    variant: {
      id: "var_9",
      sku: "JBLCHARGE4_BLACK",
      description: "JBL Charge 4 - Black",
      inventory: 70,
      brand: "JBL",
      color: "White",
      price: {
        raw: 179,
        formatted: "179.00",
        formatted_with_symbol: "$179.00",
        formatted_with_code: "179.00 USD",
      },
      is_valid: true,
    },
    image: {
      type: "image",
      source: "https://example.com/products/jbl_charge_4.jpg",
      asset_id: "asset_9",
    },
    category_id: "cat_1",
  },
  {
    id: "prod_10",
    product_id: "prod_10",
    name: "Levi's 501 Original Fit Jeans",
    product_name: "Levi's 501 Original Fit Jeans",
    sku: "LEVIS501",
    permalink: "levis-501-original-fit-jeans",
    quantity: 100,
    price: {
      raw: 89,
      formatted: "89.00",
      formatted_with_symbol: "$89.00",
      formatted_with_code: "89.00 USD",
    },
    line_total: {
      raw: 89,
      formatted: "89.00",
      formatted_with_symbol: "$89.00",
      formatted_with_code: "89.00 USD",
    },
    is_valid: true,
    product_meta: [],
    selected_options: [],
    variant: {
      id: "var_10",
      sku: "LEVIS501_BLUE",
      description: "Levi's 501 Original Fit Jeans - Blue",
      inventory: 50,
      price: {
        raw: 89,
        formatted: "89.00",
        formatted_with_symbol: "$89.00",
        formatted_with_code: "89.00 USD",
      },
      is_valid: true,
      brand: "Levi's",
      color: "Blue",
    },
    image: [
      {
        type: "image",
        source: "https://example.com/products/levis_501_front.jpg",
        asset_id: "asset_10_1",
      },
      {
        type: "image",
        source: "https://example.com/products/levis_501_back.jpg",
        asset_id: "asset_10_2",
      },
    ],
    category_id: "cat_2",
  },
  {
    id: "prod_11",
    product_id: "prod_11",
    name: "Nike Sportswear Club Fleece Hoodie",
    product_name: "Nike Sportswear Club Fleece Hoodie",
    sku: "NIKEHOODIE",
    permalink: "nike-sportswear-club-fleece-hoodie",
    quantity: 200,
    price: {
      raw: 55,
      formatted: "55.00",
      formatted_with_symbol: "$55.00",
      formatted_with_code: "55.00 USD",
    },
    line_total: {
      raw: 55,
      formatted: "55.00",
      formatted_with_symbol: "$55.00",
      formatted_with_code: "55.00 USD",
    },
    is_valid: true,
    product_meta: [],
    selected_options: [],
    variant: {
      id: "var_11",
      sku: "NIKEHOODIE_GRAY",
      description: "Nike Sportswear Club Fleece Hoodie - Gray",
      inventory: 150,
      price: {
        raw: 55,
        formatted: "55.00",
        formatted_with_symbol: "$55.00",
        formatted_with_code: "55.00 USD",
      },
      is_valid: true,
      brand: "Nike",
      color: "Gray",
    },
    image: [
      {
        type: "image",
        source: "https://example.com/products/nike_hoodie_front.jpg",
        asset_id: "asset_11_1",
      },
      {
        type: "image",
        source: "https://example.com/products/nike_hoodie_back.jpg",
        asset_id: "asset_11_2",
      },
    ],
    category_id: "cat_2",
  },
  {
    id: "prod_12",
    product_id: "prod_12",
    name: "Adidas Originals Superstar Track Jacket",
    product_name: "Adidas Originals Superstar Track Jacket",
    sku: "ADIDASJACKET",
    permalink: "adidas-originals-superstar-track-jacket",
    quantity: 120,
    price: {
      raw: 70,
      formatted: "70.00",
      formatted_with_symbol: "$70.00",
      formatted_with_code: "70.00 USD",
    },
    line_total: {
      raw: 70,
      formatted: "70.00",
      formatted_with_symbol: "$70.00",
      formatted_with_code: "70.00 USD",
    },
    is_valid: true,
    product_meta: [],
    selected_options: [],
    variant: {
      id: "var_12",
      sku: "ADIDASJACKET_BLACK",
      description: "Adidas Originals Superstar Track Jacket - Black",
      inventory: 80,
      price: {
        raw: 70,
        formatted: "70.00",
        formatted_with_symbol: "$70.00",
        formatted_with_code: "70.00 USD",
      },
      is_valid: true,
      brand: "Adidas",
      color: "Black",
    },
    image: [
      {
        type: "image",
        source: "https://example.com/products/adidas_jacket_front.jpg",
        asset_id: "asset_12_1",
      },
      {
        type: "image",
        source: "https://example.com/products/adidas_jacket_back.jpg",
        asset_id: "asset_12_2",
      },
    ],
    category_id: "cat_2",
  },
  {
    id: "prod_13",
    product_id: "prod_13",
    name: "Polo Ralph Lauren Crew Neck T-Shirt",
    product_name: "Polo Ralph Lauren Crew Neck T-Shirt",
    sku: "POLOT",
    permalink: "polo-ralph-lauren-crew-neck-t-shirt",
    quantity: 300,
    price: {
      raw: 45,
      formatted: "45.00",
      formatted_with_symbol: "$45.00",
      formatted_with_code: "45.00 USD",
    },
    line_total: {
      raw: 45,
      formatted: "45.00",
      formatted_with_symbol: "$45.00",
      formatted_with_code: "45.00 USD",
    },
    is_valid: true,
    product_meta: [],
    selected_options: [],
    variant: {
      id: "var_13",
      sku: "POLOT_WHITE",
      description: "Polo Ralph Lauren Crew Neck T-Shirt - White",
      inventory: 200,
      price: {
        raw: 45,
        formatted: "45.00",
        formatted_with_symbol: "$45.00",
        formatted_with_code: "45.00 USD",
      },
      is_valid: true,
      brand: "Polo Ralph Lauren",
      color: "White",
    },
    image: [
      {
        type: "image",
        source: "https://example.com/products/polo_tshirt_front.jpg",
        asset_id: "asset_13_1",
      },
      {
        type: "image",
        source: "https://example.com/products/polo_tshirt_back.jpg",
        asset_id: "asset_13_2",
      },
    ],
    category_id: "cat_2",
  },
  {
    id: "prod_14",
    product_id: "prod_14",
    name: "Tommy Hilfiger Iconic Flag Crew Sweatshirt",
    product_name: "Tommy Hilfiger Iconic Flag Crew Sweatshirt",
    sku: "TOMMYSWEAT",
    permalink: "tommy-hilfiger-flag-crew-sweatshirt",
    quantity: 130,
    price: {
      raw: 99,
      formatted: "99.00",
      formatted_with_symbol: "$99.00",
      formatted_with_code: "99.00 USD",
    },
    line_total: {
      raw: 99,
      formatted: "99.00",
      formatted_with_symbol: "$99.00",
      formatted_with_code: "99.00 USD",
    },
    is_valid: true,
    product_meta: [],
    selected_options: [],
    variant: {
      id: "var_14",
      sku: "TOMMYSWEAT_NAVY",
      description: "Tommy Hilfiger Iconic Flag Crew Sweatshirt - Navy",
      inventory: 100,
      price: {
        raw: 99,
        formatted: "99.00",
        formatted_with_symbol: "$99.00",
        formatted_with_code: "99.00 USD",
      },
      is_valid: true,
      brand: "Tommy Hilfiger",
      color: "Navy",
    },
    image: [
      {
        type: "image",
        source: "https://example.com/products/tommy_sweatshirt_front.jpg",
        asset_id: "asset_14_1",
      },
      {
        type: "image",
        source: "https://example.com/products/tommy_sweatshirt_back.jpg",
        asset_id: "asset_14_2",
      },
    ],
    category_id: "cat_2",
  },
  {
    id: "prod_15",
    product_id: "prod_15",
    name: "Calvin Klein Modern Cotton Stretch Trunks",
    product_name: "Calvin Klein Modern Cotton Stretch Trunks",
    sku: "CKTRUNKS",
    permalink: "calvin-klein-modern-cotton-trunks",
    quantity: 180,
    price: {
      raw: 39,
      formatted: "39.00",
      formatted_with_symbol: "$39.00",
      formatted_with_code: "39.00 USD",
    },
    line_total: {
      raw: 39,
      formatted: "39.00",
      formatted_with_symbol: "$39.00",
      formatted_with_code: "39.00 USD",
    },
    is_valid: true,
    product_meta: [],
    selected_options: [],
    variant: {
      id: "var_15",
      sku: "CKTRUNKS_GRAY",
      description: "Calvin Klein Modern Cotton Stretch Trunks - Gray",
      inventory: 130,
      price: {
        raw: 39,
        formatted: "39.00",
        formatted_with_symbol: "$39.00",
        formatted_with_code: "39.00 USD",
      },
      is_valid: true,
      brand: "Calvin Klein",
      color: "Gray",
    },
    image: [
      {
        type: "image",
        source: "https://example.com/products/ck_trunks_front.jpg",
        asset_id: "asset_15_1",
      },
      {
        type: "image",
        source: "https://example.com/products/ck_trunks_back.jpg",
        asset_id: "asset_15_2",
      },
    ],
    category_id: "cat_2",
  },
  {
    id: "prod_16",
    product_id: "prod_16",
    name: "Lululemon ABC Jogger Pants",
    product_name: "Lululemon ABC Jogger Pants",
    sku: "LULUABC",
    permalink: "lululemon-abc-jogger-pants",
    quantity: 85,
    price: {
      raw: 128,
      formatted: "128.00",
      formatted_with_symbol: "$128.00",
      formatted_with_code: "128.00 USD",
    },
    line_total: {
      raw: 128,
      formatted: "128.00",
      formatted_with_symbol: "$128.00",
      formatted_with_code: "128.00 USD",
    },
    is_valid: true,
    product_meta: [],
    selected_options: [],
    variant: {
      id: "var_16",
      sku: "LULUABC_BLACK",
      description: "Lululemon ABC Jogger Pants - Black",
      inventory: 60,
      price: {
        raw: 128,
        formatted: "128.00",
        formatted_with_symbol: "$128.00",
        formatted_with_code: "128.00 USD",
      },
      is_valid: true,
      brand: "Lululemon",
      color: "Black",
    },
    image: [
      {
        type: "image",
        source: "https://example.com/products/lulu_abc_joggers_front.jpg",
        asset_id: "asset_16_1",
      },
      {
        type: "image",
        source: "https://example.com/products/lulu_abc_joggers_back.jpg",
        asset_id: "asset_16_2",
      },
    ],
    category_id: "cat_2",
  },
  {
    id: "prod_17",
    product_id: "prod_17",
    name: "The North Face Resolve Waterproof Jacket",
    product_name: "The North Face Resolve Waterproof Jacket",
    sku: "TNFJACKET",
    permalink: "north-face-resolve-waterproof-jacket",
    quantity: 110,
    price: {
      raw: 90,
      formatted: "90.00",
      formatted_with_symbol: "$90.00",
      formatted_with_code: "90.00 USD",
    },
    line_total: {
      raw: 90,
      formatted: "90.00",
      formatted_with_symbol: "$90.00",
      formatted_with_code: "90.00 USD",
    },
    is_valid: true,
    product_meta: [],
    selected_options: [],
    variant: {
      id: "var_17",
      sku: "TNFJACKET_BLACK",
      description: "The North Face Resolve Jacket - Black",
      inventory: 90,
      price: {
        raw: 90,
        formatted: "90.00",
        formatted_with_symbol: "$90.00",
        formatted_with_code: "90.00 USD",
      },
      is_valid: true,
      brand: "The North Face",
      color: "Black",
    },
    image: [
      {
        type: "image",
        source: "https://example.com/products/tnf_jacket_front.jpg",
        asset_id: "asset_17_1",
      },
      {
        type: "image",
        source: "https://example.com/products/tnf_jacket_back.jpg",
        asset_id: "asset_17_2",
      },
    ],
    category_id: "cat_2",
  },
  {
    id: "prod_18",
    product_id: "prod_18",
    name: "Under Armour Charged Cotton T-Shirt",
    product_name: "Under Armour Charged Cotton T-Shirt",
    sku: "UATCHARGED",
    permalink: "under-armour-charged-cotton-tshirt",
    quantity: 250,
    price: {
      raw: 30,
      formatted: "30.00",
      formatted_with_symbol: "$30.00",
      formatted_with_code: "30.00 USD",
    },
    line_total: {
      raw: 30,
      formatted: "30.00",
      formatted_with_symbol: "$30.00",
      formatted_with_code: "30.00 USD",
    },
    is_valid: true,
    product_meta: [],
    selected_options: [],
    variant: {
      id: "var_18",
      sku: "UATCHARGED_BLUE",
      description: "Under Armour Charged Cotton T-Shirt - Blue",
      inventory: 200,
      price: {
        raw: 30,
        formatted: "30.00",
        formatted_with_symbol: "$30.00",
        formatted_with_code: "30.00 USD",
      },
      is_valid: true,
      brand: "Under Armour",
      color: "Blue",
    },
    image: [
      {
        type: "image",
        source: "https://example.com/products/ua_charged_tshirt_front.jpg",
        asset_id: "asset_18_1",
      },
      {
        type: "image",
        source: "https://example.com/products/ua_charged_tshirt_back.jpg",
        asset_id: "asset_18_2",
      },
    ],
    category_id: "cat_2",
  },
  {
    id: "prod_19",
    product_id: "prod_19",
    name: "Patagonia Down Sweater Vest",
    product_name: "Patagonia Down Sweater Vest",
    sku: "PATAGONIAVEST",
    permalink: "patagonia-down-sweater-vest",
    quantity: 50,
    price: {
      raw: 179,
      formatted: "179.00",
      formatted_with_symbol: "$179.00",
      formatted_with_code: "179.00 USD",
    },
    line_total: {
      raw: 179,
      formatted: "179.00",
      formatted_with_symbol: "$179.00",
      formatted_with_code: "179.00 USD",
    },
    is_valid: true,
    product_meta: [],
    selected_options: [],
    variant: {
      id: "var_19",
      sku: "PATAGONIAVEST_NAVY",
      description: "Patagonia Down Sweater Vest - Navy",
      inventory: 40,
      price: {
        raw: 179,
        formatted: "179.00",
        formatted_with_symbol: "$179.00",
        formatted_with_code: "179.00 USD",
      },
      is_valid: true,
      brand: "Patagonia",
      color: "Navy",
    },
    image: [
      {
        type: "image",
        source: "https://example.com/products/patagonia_vest_front.jpg",
        asset_id: "asset_19_1",
      },
      {
        type: "image",
        source: "https://example.com/products/patagonia_vest_back.jpg",
        asset_id: "asset_19_2",
      },
    ],
    category_id: "cat_2",
  },
  {
    id: "prod_20",
    product_id: "prod_20",
    name: "Tommy Hilfiger Men's Slim Fit Suit",
    product_name: "Tommy Hilfiger Men's Slim Fit Suit",
    sku: "TOMMYSUIT",
    permalink: "tommy-hilfiger-mens-slim-fit-suit",
    quantity: 50,
    price: {
      raw: 299,
      formatted: "299.00",
      formatted_with_symbol: "$299.00",
      formatted_with_code: "299.00 USD",
    },
    line_total: {
      raw: 299,
      formatted: "299.00",
      formatted_with_symbol: "$299.00",
      formatted_with_code: "299.00 USD",
    },
    is_valid: true,
    product_meta: [],
    selected_options: [],
    variant: {
      id: "var_20",
      sku: "TOMMYSUIT_NAVY",
      description: "Tommy Hilfiger Men's Slim Fit Suit - Navy",
      inventory: 40,
      price: {
        raw: 299,
        formatted: "299.00",
        formatted_with_symbol: "$299.00",
        formatted_with_code: "299.00 USD",
      },
      is_valid: true,
      brand: "Tommy Hilfiger",
      color: "Navy",
    },
    image: [
      {
        type: "image",
        source: "https://example.com/products/tommy_slim_fit_suit_front.jpg",
        asset_id: "asset_20_1",
      },
      {
        type: "image",
        source: "https://example.com/products/tommy_slim_fit_suit_back.jpg",
        asset_id: "asset_20_2",
      },
    ],
    category_id: "cat_3",
  },
  {
    id: "prod_21",
    product_id: "prod_21",
    name: "Calvin Klein Men's Classic Fit Dress Shirt",
    product_name: "Calvin Klein Men's Classic Fit Dress Shirt",
    sku: "CKDRESSSHIRT",
    permalink: "calvin-klein-mens-classic-fit-dress-shirt",
    quantity: 120,
    price: {
      raw: 79,
      formatted: "79.00",
      formatted_with_symbol: "$79.00",
      formatted_with_code: "79.00 USD",
    },
    line_total: {
      raw: 79,
      formatted: "79.00",
      formatted_with_symbol: "$79.00",
      formatted_with_code: "79.00 USD",
    },
    is_valid: true,
    product_meta: [],
    selected_options: [],
    variant: {
      id: "var_21",
      sku: "CKDRESSSHIRT_WHITE",
      description: "Calvin Klein Men's Classic Fit Dress Shirt - White",
      inventory: 90,
      price: {
        raw: 79,
        formatted: "79.00",
        formatted_with_symbol: "$79.00",
        formatted_with_code: "79.00 USD",
      },
      is_valid: true,
      brand: "Calvin Klein",
      color: "White",
    },
    image: [
      {
        type: "image",
        source: "https://example.com/products/ck_dress_shirt_front.jpg",
        asset_id: "asset_21_1",
      },
      {
        type: "image",
        source: "https://example.com/products/ck_dress_shirt_back.jpg",
        asset_id: "asset_21_2",
      },
    ],
    category_id: "cat_3",
  },
  {
    id: "prod_22",
    product_id: "prod_22",
    name: "Ralph Lauren Polo Shirt",
    product_name: "Ralph Lauren Polo Shirt",
    sku: "RALPHPOLO",
    permalink: "ralph-lauren-polo-shirt",
    quantity: 200,
    price: {
      raw: 85,
      formatted: "85.00",
      formatted_with_symbol: "$85.00",
      formatted_with_code: "85.00 USD",
    },
    line_total: {
      raw: 85,
      formatted: "85.00",
      formatted_with_symbol: "$85.00",
      formatted_with_code: "85.00 USD",
    },
    is_valid: true,
    product_meta: [],
    selected_options: [],
    variant: {
      id: "var_22",
      sku: "RALPHPOLO_BLUE",
      description: "Ralph Lauren Polo Shirt - Blue",
      inventory: 150,
      price: {
        raw: 85,
        formatted: "85.00",
        formatted_with_symbol: "$85.00",
        formatted_with_code: "85.00 USD",
      },
      is_valid: true,
      brand: "Ralph Lauren",
      color: "Blue",
    },
    image: [
      {
        type: "image",
        source: "https://example.com/products/ralph_polo_shirt_front.jpg",
        asset_id: "asset_22_1",
      },
      {
        type: "image",
        source: "https://example.com/products/ralph_polo_shirt_back.jpg",
        asset_id: "asset_22_2",
      },
    ],
    category_id: "cat_3",
  },
  {
    id: "prod_23",
    product_id: "prod_23",
    name: "Levi's Men's 511 Slim Fit Jeans",
    product_name: "Levi's Men's 511 Slim Fit Jeans",
    sku: "LEVIS511",
    permalink: "levis-mens-511-slim-fit-jeans",
    quantity: 80,
    price: {
      raw: 98,
      formatted: "98.00",
      formatted_with_symbol: "$98.00",
      formatted_with_code: "98.00 USD",
    },
    line_total: {
      raw: 98,
      formatted: "98.00",
      formatted_with_symbol: "$98.00",
      formatted_with_code: "98.00 USD",
    },
    is_valid: true,
    product_meta: [],
    selected_options: [],
    variant: {
      id: "var_23",
      sku: "LEVIS511_BLACK",
      description: "Levi's Men's 511 Slim Fit Jeans - Black",
      inventory: 60,
      price: {
        raw: 98,
        formatted: "98.00",
        formatted_with_symbol: "$98.00",
        formatted_with_code: "98.00 USD",
      },
      is_valid: true,
      brand: "Levi's",
      color: "Black",
    },
    image: [
      {
        type: "image",
        source: "https://example.com/products/levis_511_jeans_front.jpg",
        asset_id: "asset_23_1",
      },
      {
        type: "image",
        source: "https://example.com/products/levis_511_jeans_back.jpg",
        asset_id: "asset_23_2",
      },
    ],
    category_id: "cat_3",
  },
  {
    id: "prod_24",
    product_id: "prod_24",
    name: "Nike Men's Sportswear Club Fleece Pants",
    product_name: "Nike Men's Sportswear Club Fleece Pants",
    sku: "NIKEFLEECE",
    permalink: "nike-mens-sportswear-club-fleece-pants",
    quantity: 90,
    price: {
      raw: 55,
      formatted: "55.00",
      formatted_with_symbol: "$55.00",
      formatted_with_code: "55.00 USD",
    },
    line_total: {
      raw: 55,
      formatted: "55.00",
      formatted_with_symbol: "$55.00",
      formatted_with_code: "55.00 USD",
    },
    is_valid: true,
    product_meta: [],
    selected_options: [],
    variant: {
      id: "var_24",
      sku: "NIKEFLEECE_GRAY",
      description: "Nike Men's Sportswear Club Fleece Pants - Gray",
      inventory: 70,
      price: {
        raw: 55,
        formatted: "55.00",
        formatted_with_symbol: "$55.00",
        formatted_with_code: "55.00 USD",
      },
      is_valid: true,
      brand: "Nike",
      color: "Gray",
    },
    image: [
      {
        type: "image",
        source: "https://example.com/products/nike_fleece_pants_front.jpg",
        asset_id: "asset_24_1",
      },
      {
        type: "image",
        source: "https://example.com/products/nike_fleece_pants_back.jpg",
        asset_id: "asset_24_2",
      },
    ],
    category_id: "cat_3",
  },
  {
    id: "prod_25",
    product_id: "prod_25",
    name: "Timberland Men's Waterproof Boots",
    product_name: "Timberland Men's Waterproof Boots",
    sku: "TIMBERLANDBOOTS",
    permalink: "timberland-mens-waterproof-boots",
    quantity: 70,
    price: {
      raw: 170,
      formatted: "170.00",
      formatted_with_symbol: "$170.00",
      formatted_with_code: "170.00 USD",
    },
    line_total: {
      raw: 170,
      formatted: "170.00",
      formatted_with_symbol: "$170.00",
      formatted_with_code: "170.00 USD",
    },
    is_valid: true,
    product_meta: [],
    selected_options: [],
    variant: {
      id: "var_25",
      sku: "TIMBERLANDBOOTS_BROWN",
      description: "Timberland Men's Waterproof Boots - Brown",
      inventory: 50,
      price: {
        raw: 170,
        formatted: "170.00",
        formatted_with_symbol: "$170.00",
        formatted_with_code: "170.00 USD",
      },
      is_valid: true,
      brand: "Timberland",
      color: "Brown",
    },
    image: [
      {
        type: "image",
        source: "https://example.com/products/timberland_boots_front.jpg",
        asset_id: "asset_25_1",
      },
      {
        type: "image",
        source: "https://example.com/products/timberland_boots_back.jpg",
        asset_id: "asset_25_2",
      },
    ],
    category_id: "cat_3",
  },
  {
    id: "prod_26",
    product_id: "prod_26",
    name: "Hugo Boss Men's Leather Belt",
    product_name: "Hugo Boss Men's Leather Belt",
    sku: "HUGOBELT",
    permalink: "hugo-boss-mens-leather-belt",
    quantity: 150,
    price: {
      raw: 69,
      formatted: "69.00",
      formatted_with_symbol: "$69.00",
      formatted_with_code: "69.00 USD",
    },
    line_total: {
      raw: 69,
      formatted: "69.00",
      formatted_with_symbol: "$69.00",
      formatted_with_code: "69.00 USD",
    },
    is_valid: true,
    product_meta: [],
    selected_options: [],
    variant: {
      id: "var_26",
      sku: "HUGOBELT_BLACK",
      description: "Hugo Boss Men's Leather Belt - Black",
      inventory: 100,
      price: {
        raw: 69,
        formatted: "69.00",
        formatted_with_symbol: "$69.00",
        formatted_with_code: "69.00 USD",
      },
      is_valid: true,
      brand: "Hugo Boss",
      color: "Black",
    },
    image: [
      {
        type: "image",
        source: "https://example.com/products/hugo_boss_belt_front.jpg",
        asset_id: "asset_26_1",
      },
      {
        type: "image",
        source: "https://example.com/products/hugo_boss_belt_back.jpg",
        asset_id: "asset_26_2",
      },
    ],
    category_id: "cat_3",
  },
  {
    id: "prod_27",
    product_id: "prod_27",
    name: "Under Armour Men's HeatGear Compression Shirt",
    product_name: "Under Armour Men's HeatGear Compression Shirt",
    sku: "UAHEATGEAR",
    permalink: "under-armour-mens-heatgear-compression-shirt",
    quantity: 130,
    price: {
      raw: 35,
      formatted: "35.00",
      formatted_with_symbol: "$35.00",
      formatted_with_code: "35.00 USD",
    },
    line_total: {
      raw: 35,
      formatted: "35.00",
      formatted_with_symbol: "$35.00",
      formatted_with_code: "35.00 USD",
    },
    is_valid: true,
    product_meta: [],
    selected_options: [],
    variant: {
      id: "var_27",
      sku: "UAHEATGEAR_GRAY",
      description: "Under Armour Men's HeatGear Compression Shirt - Gray",
      inventory: 100,
      price: {
        raw: 35,
        formatted: "35.00",
        formatted_with_symbol: "$35.00",
        formatted_with_code: "35.00 USD",
      },
      is_valid: true,
      brand: "Under Armour",
      color: "Gray",
    },
    image: [
      {
        type: "image",
        source: "https://example.com/products/ua_heatgear_shirt_front.jpg",
        asset_id: "asset_27_1",
      },
      {
        type: "image",
        source: "https://example.com/products/ua_heatgear_shirt_back.jpg",
        asset_id: "asset_27_2",
      },
    ],
    category_id: "cat_3",
  },
  {
    id: "prod_28",
    product_id: "prod_28",
    name: "Giorgio Armani Men's Wool Blazer",
    product_name: "Giorgio Armani Men's Wool Blazer",
    sku: "ARMANIBLAZER",
    permalink: "giorgio-armani-mens-wool-blazer",
    quantity: 30,
    price: {
      raw: 599,
      formatted: "599.00",
      formatted_with_symbol: "$599.00",
      formatted_with_code: "599.00 USD",
    },
    line_total: {
      raw: 599,
      formatted: "599.00",
      formatted_with_symbol: "$599.00",
      formatted_with_code: "599.00 USD",
    },
    is_valid: true,
    product_meta: [],
    selected_options: [],
    variant: {
      id: "var_28",
      sku: "ARMANIBLAZER_GRAY",
      description: "Giorgio Armani Men's Wool Blazer - Gray",
      inventory: 20,
      price: {
        raw: 599,
        formatted: "599.00",
        formatted_with_symbol: "$599.00",
        formatted_with_code: "599.00 USD",
      },
      is_valid: true,
      brand: "Giorgio Armani",
      color: "Gray",
    },
    image: [
      {
        type: "image",
        source: "https://example.com/products/armani_blazer_front.jpg",
        asset_id: "asset_28_1",
      },
      {
        type: "image",
        source: "https://example.com/products/armani_blazer_back.jpg",
        asset_id: "asset_28_2",
      },
    ],
    category_id: "cat_3",
  },
  {
    id: "prod_29",
    product_id: "prod_29",
    name: "Puma Men's Essential Logo T-Shirt",
    product_name: "Puma Men's Essential Logo T-Shirt",
    sku: "PUMATSHIRT",
    permalink: "puma-mens-essential-logo-tshirt",
    quantity: 200,
    price: {
      raw: 25,
      formatted: "25.00",
      formatted_with_symbol: "$25.00",
      formatted_with_code: "25.00 USD",
    },
    line_total: {
      raw: 25,
      formatted: "25.00",
      formatted_with_symbol: "$25.00",
      formatted_with_code: "25.00 USD",
    },
    is_valid: true,
    product_meta: [],
    selected_options: [],
    variant: {
      id: "var_29",
      sku: "PUMATSHIRT_BLACK",
      description: "Puma Men's Essential Logo T-Shirt - Black",
      inventory: 150,
      price: {
        raw: 25,
        formatted: "25.00",
        formatted_with_symbol: "$25.00",
        formatted_with_code: "25.00 USD",
      },
      is_valid: true,
      brand: "Puma",
      color: "Black",
    },
    image: [
      {
        type: "image",
        source: "https://example.com/products/puma_tshirt_front.jpg",
        asset_id: "asset_29_1",
      },
      {
        type: "image",
        source: "https://example.com/products/puma_tshirt_back.jpg",
        asset_id: "asset_29_2",
      },
    ],
    category_id: "cat_3",
  },
  {
    id: "prod_30",
    product_id: "prod_30",
    name: "Michael Kors Women's Jet Set Tote",
    product_name: "Michael Kors Women's Jet Set Tote",
    sku: "MKJETSETTOTE",
    permalink: "michael-kors-womens-jet-set-tote",
    quantity: 50,
    price: {
      raw: 198,
      formatted: "198.00",
      formatted_with_symbol: "$198.00",
      formatted_with_code: "198.00 USD",
    },
    line_total: {
      raw: 198,
      formatted: "198.00",
      formatted_with_symbol: "$198.00",
      formatted_with_code: "198.00 USD",
    },
    is_valid: true,
    product_meta: [],
    selected_options: [],
    variant: {
      id: "var_30",
      sku: "MKJETSETTOTE_BLACK",
      description: "Michael Kors Women's Jet Set Tote - Black",
      inventory: 40,
      price: {
        raw: 198,
        formatted: "198.00",
        formatted_with_symbol: "$198.00",
        formatted_with_code: "198.00 USD",
      },
      is_valid: true,
      brand: "Michael Kors",
      color: "Black",
    },
    image: [
      {
        type: "image",
        source: "https://example.com/products/mk_jetset_tote_front.jpg",
        asset_id: "asset_30_1",
      },
      {
        type: "image",
        source: "https://example.com/products/mk_jetset_tote_back.jpg",
        asset_id: "asset_30_2",
      },
    ],
    category_id: "cat_4",
  },
  {
    id: "prod_31",
    product_id: "prod_31",
    name: "Levi's Women's 711 Skinny Jeans",
    product_name: "Levi's Women's 711 Skinny Jeans",
    sku: "LEVIS711",
    permalink: "levis-womens-711-skinny-jeans",
    quantity: 90,
    price: {
      raw: 88,
      formatted: "88.00",
      formatted_with_symbol: "$88.00",
      formatted_with_code: "88.00 USD",
    },
    line_total: {
      raw: 88,
      formatted: "88.00",
      formatted_with_symbol: "$88.00",
      formatted_with_code: "88.00 USD",
    },
    is_valid: true,
    product_meta: [],
    selected_options: [],
    variant: {
      id: "var_31",
      sku: "LEVIS711_BLUE",
      description: "Levi's Women's 711 Skinny Jeans - Blue",
      inventory: 70,
      price: {
        raw: 88,
        formatted: "88.00",
        formatted_with_symbol: "$88.00",
        formatted_with_code: "88.00 USD",
      },
      is_valid: true,
      brand: "Levi's",
      color: "Blue",
    },
    image: [
      {
        type: "image",
        source: "https://example.com/products/levis_711_jeans_front.jpg",
        asset_id: "asset_31_1",
      },
      {
        type: "image",
        source: "https://example.com/products/levis_711_jeans_back.jpg",
        asset_id: "asset_31_2",
      },
    ],
    category_id: "cat_4",
  },
  {
    id: "prod_32",
    product_id: "prod_32",
    name: "Gucci Women's Ace Sneaker",
    product_name: "Gucci Women's Ace Sneaker",
    sku: "GUCCIACE",
    permalink: "gucci-womens-ace-sneaker",
    quantity: 40,
    price: {
      raw: 580,
      formatted: "580.00",
      formatted_with_symbol: "$580.00",
      formatted_with_code: "580.00 USD",
    },
    line_total: {
      raw: 580,
      formatted: "580.00",
      formatted_with_symbol: "$580.00",
      formatted_with_code: "580.00 USD",
    },
    is_valid: true,
    product_meta: [],
    selected_options: [],
    variant: {
      id: "var_32",
      sku: "GUCCIACE_WHITE",
      description: "Gucci Women's Ace Sneaker - White",
      inventory: 30,
      price: {
        raw: 580,
        formatted: "580.00",
        formatted_with_symbol: "$580.00",
        formatted_with_code: "580.00 USD",
      },
      is_valid: true,
      brand: "Gucci",
      color: "White",
    },
    image: [
      {
        type: "image",
        source: "https://example.com/products/gucci_ace_sneaker_front.jpg",
        asset_id: "asset_32_1",
      },
      {
        type: "image",
        source: "https://example.com/products/gucci_ace_sneaker_back.jpg",
        asset_id: "asset_32_2",
      },
    ],
    category_id: "cat_4",
  },
  {
    id: "prod_33",
    product_id: "prod_33",
    name: "Chanel Women's Classic Flap Bag",
    product_name: "Chanel Women's Classic Flap Bag",
    sku: "CHANELFLAP",
    permalink: "chanel-womens-classic-flap-bag",
    quantity: 20,
    price: {
      raw: 5200,
      formatted: "5200.00",
      formatted_with_symbol: "$5200.00",
      formatted_with_code: "5200.00 USD",
    },
    line_total: {
      raw: 5200,
      formatted: "5200.00",
      formatted_with_symbol: "$5200.00",
      formatted_with_code: "5200.00 USD",
    },
    is_valid: true,
    product_meta: [],
    selected_options: [],
    variant: {
      id: "var_33",
      sku: "CHANELFLAP_BLACK",
      description: "Chanel Women's Classic Flap Bag - Black",
      inventory: 15,
      price: {
        raw: 5200,
        formatted: "5200.00",
        formatted_with_symbol: "$5200.00",
        formatted_with_code: "5200.00 USD",
      },
      is_valid: true,
      brand: "Chanel",
      color: "Black",
    },
    image: [
      {
        type: "image",
        source: "https://example.com/products/chanel_flap_bag_front.jpg",
        asset_id: "asset_33_1",
      },
      {
        type: "image",
        source: "https://example.com/products/chanel_flap_bag_back.jpg",
        asset_id: "asset_33_2",
      },
    ],
    category_id: "cat_4",
  },
  {
    id: "prod_34",
    product_id: "prod_34",
    name: "Prada Women's Leather Ankle Boots",
    product_name: "Prada Women's Leather Ankle Boots",
    sku: "PRADAANKLEBOOTS",
    permalink: "prada-womens-leather-ankle-boots",
    quantity: 30,
    price: {
      raw: 990,
      formatted: "990.00",
      formatted_with_symbol: "$990.00",
      formatted_with_code: "990.00 USD",
    },
    line_total: {
      raw: 990,
      formatted: "990.00",
      formatted_with_symbol: "$990.00",
      formatted_with_code: "990.00 USD",
    },
    is_valid: true,
    product_meta: [],
    selected_options: [],
    variant: {
      id: "var_34",
      sku: "PRADAANKLEBOOTS_BLACK",
      description: "Prada Women's Leather Ankle Boots - Black",
      inventory: 20,
      price: {
        raw: 990,
        formatted: "990.00",
        formatted_with_symbol: "$990.00",
        formatted_with_code: "990.00 USD",
      },
      is_valid: true,
      brand: "Prada",
      color: "Black",
    },
    image: [
      {
        type: "image",
        source: "https://example.com/products/prada_ankle_boots_front.jpg",
        asset_id: "asset_34_1",
      },
      {
        type: "image",
        source: "https://example.com/products/prada_ankle_boots_back.jpg",
        asset_id: "asset_34_2",
      },
    ],
    category_id: "cat_4",
  },
  {
    id: "prod_35",
    product_id: "prod_35",
    name: "Burberry Women's Trench Coat",
    product_name: "Burberry Women's Trench Coat",
    sku: "BURBERRYTRENCH",
    permalink: "burberry-womens-trench-coat",
    quantity: 40,
    price: {
      raw: 1995,
      formatted: "1995.00",
      formatted_with_symbol: "$1995.00",
      formatted_with_code: "1995.00 USD",
    },
    line_total: {
      raw: 1995,
      formatted: "1995.00",
      formatted_with_symbol: "$1995.00",
      formatted_with_code: "1995.00 USD",
    },
    is_valid: true,
    product_meta: [],
    selected_options: [],
    variant: {
      id: "var_35",
      sku: "BURBERRYTRENCH_BEIGE",
      description: "Burberry Women's Trench Coat - Beige",
      inventory: 30,
      price: {
        raw: 1995,
        formatted: "1995.00",
        formatted_with_symbol: "$1995.00",
        formatted_with_code: "1995.00 USD",
      },
      is_valid: true,
      brand: "Burberry",
      color: "Beige",
    },
    image: [
      {
        type: "image",
        source: "https://example.com/products/burberry_trench_coat_front.jpg",
        asset_id: "asset_35_1",
      },
      {
        type: "image",
        source: "https://example.com/products/burberry_trench_coat_back.jpg",
        asset_id: "asset_35_2",
      },
    ],
    category_id: "cat_4",
  },
  {
    id: "prod_36",
    product_id: "prod_36",
    name: "Versace Women's Baroque Print Silk Scarf",
    product_name: "Versace Women's Baroque Print Silk Scarf",
    sku: "VERSACESILKSCARF",
    permalink: "versace-womens-baroque-print-silk-scarf",
    quantity: 50,
    price: {
      raw: 495,
      formatted: "495.00",
      formatted_with_symbol: "$495.00",
      formatted_with_code: "495.00 USD",
    },
    line_total: {
      raw: 495,
      formatted: "495.00",
      formatted_with_symbol: "$495.00",
      formatted_with_code: "495.00 USD",
    },
    is_valid: true,
    product_meta: [],
    selected_options: [],
    variant: {
      id: "var_36",
      sku: "VERSACESILKSCARF_GOLD",
      description: "Versace Women's Baroque Print Silk Scarf - Gold",
      inventory: 40,
      price: {
        raw: 495,
        formatted: "495.00",
        formatted_with_symbol: "$495.00",
        formatted_with_code: "495.00 USD",
      },
      is_valid: true,
      brand: "Versace",
      color: "Gold",
    },
    image: [
      {
        type: "image",
        source: "https://example.com/products/versace_silk_scarf_front.jpg",
        asset_id: "asset_36_1",
      },
      {
        type: "image",
        source: "https://example.com/products/versace_silk_scarf_back.jpg",
        asset_id: "asset_36_2",
      },
    ],
    category_id: "cat_4",
  },
  {
    id: "prod_37",
    product_id: "prod_37",
    name: "Zara Women's Oversized Blazer",
    product_name: "Zara Women's Oversized Blazer",
    sku: "ZARABLAZER",
    permalink: "zara-womens-oversized-blazer",
    quantity: 80,
    price: {
      raw: 129,
      formatted: "129.00",
      formatted_with_symbol: "$129.00",
      formatted_with_code: "129.00 USD",
    },
    line_total: {
      raw: 129,
      formatted: "129.00",
      formatted_with_symbol: "$129.00",
      formatted_with_code: "129.00 USD",
    },
    is_valid: true,
    product_meta: [],
    selected_options: [],
    variant: {
      id: "var_37",
      sku: "ZARABLAZER_GRAY",
      description: "Zara Women's Oversized Blazer - Gray",
      inventory: 60,
      price: {
        raw: 129,
        formatted: "129.00",
        formatted_with_symbol: "$129.00",
        formatted_with_code: "129.00 USD",
      },
      is_valid: true,
      brand: "Zara",
      color: "Gray",
    },
    image: [
      {
        type: "image",
        source: "https://example.com/products/zara_blazer_front.jpg",
        asset_id: "asset_37_1",
      },
      {
        type: "image",
        source: "https://example.com/products/zara_blazer_back.jpg",
        asset_id: "asset_37_2",
      },
    ],
    category_id: "cat_4",
  },
  {
    id: "prod_38",
    product_id: "prod_38",
    name: "H&M Women's Knit Sweater",
    product_name: "H&M Women's Knit Sweater",
    sku: "HMSWEATER",
    permalink: "hm-womens-knit-sweater",
    quantity: 120,
    price: {
      raw: 29,
      formatted: "29.00",
      formatted_with_symbol: "$29.00",
      formatted_with_code: "29.00 USD",
    },
    line_total: {
      raw: 29,
      formatted: "29.00",
      formatted_with_symbol: "$29.00",
      formatted_with_code: "29.00 USD",
    },
    is_valid: true,
    product_meta: [],
    selected_options: [],
    variant: {
      id: "var_38",
      sku: "HMSWEATER_WHITE",
      description: "H&M Women's Knit Sweater - White",
      inventory: 100,
      price: {
        raw: 29,
        formatted: "29.00",
        formatted_with_symbol: "$29.00",
        formatted_with_code: "29.00 USD",
      },
      is_valid: true,
      brand: "H&M",
      color: "White",
    },
    image: [
      {
        type: "image",
        source: "https://example.com/products/hm_knit_sweater_front.jpg",
        asset_id: "asset_38_1",
      },
      {
        type: "image",
        source: "https://example.com/products/hm_knit_sweater_back.jpg",
        asset_id: "asset_38_2",
      },
    ],
    category_id: "cat_4",
  },
  {
    id: "prod_39",
    product_id: "prod_39",
    name: "Dior Women's Saddle Bag",
    product_name: "Dior Women's Saddle Bag",
    sku: "DIORSADDLEBAG",
    permalink: "dior-womens-saddle-bag",
    quantity: 20,
    price: {
      raw: 3200,
      formatted: "3200.00",
      formatted_with_symbol: "$3200.00",
      formatted_with_code: "3200.00 USD",
    },
    line_total: {
      raw: 3200,
      formatted: "3200.00",
      formatted_with_symbol: "$3200.00",
      formatted_with_code: "3200.00 USD",
    },
    is_valid: true,
    product_meta: [],
    selected_options: [],
    variant: {
      id: "var_39",
      sku: "DIORSADDLEBAG_BLACK",
      description: "Dior Women's Saddle Bag - Black",
      inventory: 15,
      price: {
        raw: 3200,
        formatted: "3200.00",
        formatted_with_symbol: "$3200.00",
        formatted_with_code: "3200.00 USD",
      },
      is_valid: true,
      brand: "Dior",
      color: "Black",
    },
    image: [
      {
        type: "image",
        source: "https://example.com/products/dior_saddle_bag_front.jpg",
        asset_id: "asset_39_1",
      },
      {
        type: "image",
        source: "https://example.com/products/dior_saddle_bag_back.jpg",
        asset_id: "asset_39_2",
      },
    ],
    category_id: "cat_4",
  },
  {
    id: "prod_40",
    product_id: "prod_40",
    name: "Omron Platinum Blood Pressure Monitor",
    product_name: "Omron Platinum Blood Pressure Monitor",
    sku: "OMRONBP",
    permalink: "omron-platinum-blood-pressure-monitor",
    quantity: 60,
    price: {
      raw: 199,
      formatted: "199.00",
      formatted_with_symbol: "$199.00",
      formatted_with_code: "199.00 USD",
    },
    line_total: {
      raw: 199,
      formatted: "199.00",
      formatted_with_symbol: "$199.00",
      formatted_with_code: "199.00 USD",
    },
    is_valid: true,
    product_meta: [],
    selected_options: [],
    variant: {
      id: "var_40",
      sku: "OMRONBP_BLACK",
      description: "Omron Platinum Blood Pressure Monitor - Black",
      inventory: 50,
      price: {
        raw: 199,
        formatted: "199.00",
        formatted_with_symbol: "$199.00",
        formatted_with_code: "199.00 USD",
      },
      is_valid: true,
      brand: "Omron",
      color: "Black",
    },
    image: [
      {
        type: "image",
        source: "https://example.com/products/omron_bp_monitor_front.jpg",
        asset_id: "asset_40_1",
      },
      {
        type: "image",
        source: "https://example.com/products/omron_bp_monitor_back.jpg",
        asset_id: "asset_40_2",
      },
    ],
    category_id: "cat_5",
  },
  {
    id: "prod_41",
    product_id: "prod_41",
    name: "Fitbit Charge 5 Fitness & Health Tracker",
    product_name: "Fitbit Charge 5 Fitness & Health Tracker",
    sku: "FITBITCHARGE5",
    permalink: "fitbit-charge-5-health-tracker",
    quantity: 80,
    price: {
      raw: 149,
      formatted: "149.00",
      formatted_with_symbol: "$149.00",
      formatted_with_code: "149.00 USD",
    },
    line_total: {
      raw: 149,
      formatted: "149.00",
      formatted_with_symbol: "$149.00",
      formatted_with_code: "149.00 USD",
    },
    is_valid: true,
    product_meta: [],
    selected_options: [],
    variant: {
      id: "var_41",
      sku: "FITBITCHARGE5_BLACK",
      description: "Fitbit Charge 5 - Black",
      inventory: 70,
      price: {
        raw: 149,
        formatted: "149.00",
        formatted_with_symbol: "$149.00",
        formatted_with_code: "149.00 USD",
      },
      is_valid: true,
      brand: "Fitbit",
      color: "Black",
    },
    image: [
      {
        type: "image",
        source: "https://example.com/products/fitbit_charge5_front.jpg",
        asset_id: "asset_41_1",
      },
      {
        type: "image",
        source: "https://example.com/products/fitbit_charge5_back.jpg",
        asset_id: "asset_41_2",
      },
    ],
    category_id: "cat_5",
  },
  {
    id: "prod_42",
    product_id: "prod_42",
    name: "Withings Body+ Digital Wi-Fi Smart Scale",
    product_name: "Withings Body+ Digital Wi-Fi Smart Scale",
    sku: "WITHINGSCALE",
    permalink: "withings-body-plus-smart-scale",
    quantity: 65,
    price: {
      raw: 99,
      formatted: "99.00",
      formatted_with_symbol: "$99.00",
      formatted_with_code: "99.00 USD",
    },
    line_total: {
      raw: 99,
      formatted: "99.00",
      formatted_with_symbol: "$99.00",
      formatted_with_code: "99.00 USD",
    },
    is_valid: true,
    product_meta: [],
    selected_options: [],
    variant: {
      id: "var_42",
      sku: "WITHINGSCALE_WHITE",
      description: "Withings Body+ Digital Wi-Fi Smart Scale - White",
      inventory: 50,
      price: {
        raw: 99,
        formatted: "99.00",
        formatted_with_symbol: "$99.00",
        formatted_with_code: "99.00 USD",
      },
      is_valid: true,
      brand: "Withings",
      color: "White",
    },
    image: [
      {
        type: "image",
        source: "https://example.com/products/withings_scale_front.jpg",
        asset_id: "asset_42_1",
      },
      {
        type: "image",
        source: "https://example.com/products/withings_scale_back.jpg",
        asset_id: "asset_42_2",
      },
    ],
    category_id: "cat_5",
  },
  {
    id: "prod_43",
    product_id: "prod_43",
    name: "Theragun Elite Percussive Therapy Device",
    product_name: "Theragun Elite Percussive Therapy Device",
    sku: "THERAGUNELITE",
    permalink: "theragun-elite-percussive-therapy-device",
    quantity: 40,
    price: {
      raw: 399,
      formatted: "399.00",
      formatted_with_symbol: "$399.00",
      formatted_with_code: "399.00 USD",
    },
    line_total: {
      raw: 399,
      formatted: "399.00",
      formatted_with_symbol: "$399.00",
      formatted_with_code: "399.00 USD",
    },
    is_valid: true,
    product_meta: [],
    selected_options: [],
    variant: {
      id: "var_43",
      sku: "THERAGUNELITE_BLACK",
      description: "Theragun Elite - Black",
      inventory: 35,
      price: {
        raw: 399,
        formatted: "399.00",
        formatted_with_symbol: "$399.00",
        formatted_with_code: "399.00 USD",
      },
      is_valid: true,
      brand: "Theragun",
      color: "Black",
    },
    image: [
      {
        type: "image",
        source: "https://example.com/products/theragun_elite_front.jpg",
        asset_id: "asset_43_1",
      },
      {
        type: "image",
        source: "https://example.com/products/theragun_elite_back.jpg",
        asset_id: "asset_43_2",
      },
    ],
    category_id: "cat_5",
  },
  {
    id: "prod_44",
    product_id: "prod_44",
    name: "Apple Watch Series 7",
    product_name: "Apple Watch Series 7",
    sku: "APPLEWATCH7",
    permalink: "apple-watch-series-7",
    quantity: 90,
    price: {
      raw: 429,
      formatted: "429.00",
      formatted_with_symbol: "$429.00",
      formatted_with_code: "429.00 USD",
    },
    line_total: {
      raw: 429,
      formatted: "429.00",
      formatted_with_symbol: "$429.00",
      formatted_with_code: "429.00 USD",
    },
    is_valid: true,
    product_meta: [],
    selected_options: [],
    variant: {
      id: "var_44",
      sku: "APPLEWATCH7_SILVER",
      description: "Apple Watch Series 7 - Silver",
      inventory: 80,
      price: {
        raw: 429,
        formatted: "429.00",
        formatted_with_symbol: "$429.00",
        formatted_with_code: "429.00 USD",
      },
      is_valid: true,
      brand: "Apple",
      color: "Silver",
    },
    image: [
      {
        type: "image",
        source: "https://example.com/products/apple_watch_7_front.jpg",
        asset_id: "asset_44_1",
      },
      {
        type: "image",
        source: "https://example.com/products/apple_watch_7_back.jpg",
        asset_id: "asset_44_2",
      },
    ],
    category_id: "cat_5",
  },
  {
    id: "prod_45",
    product_id: "prod_45",
    name: "Philips Sonicare DiamondClean Electric Toothbrush",
    product_name: "Philips Sonicare DiamondClean Electric Toothbrush",
    sku: "SONICARETOOTHBRUSH",
    permalink: "philips-sonicare-diamondclean-toothbrush",
    quantity: 70,
    price: {
      raw: 229,
      formatted: "229.00",
      formatted_with_symbol: "$229.00",
      formatted_with_code: "229.00 USD",
    },
    line_total: {
      raw: 229,
      formatted: "229.00",
      formatted_with_symbol: "$229.00",
      formatted_with_code: "229.00 USD",
    },
    is_valid: true,
    product_meta: [],
    selected_options: [],
    variant: {
      id: "var_45",
      sku: "SONICARETOOTHBRUSH_WHITE",
      description: "Philips Sonicare DiamondClean - White",
      inventory: 60,
      price: {
        raw: 229,
        formatted: "229.00",
        formatted_with_symbol: "$229.00",
        formatted_with_code: "229.00 USD",
      },
      is_valid: true,
      brand: "Philips",
      color: "White",
    },
    image: [
      {
        type: "image",
        source: "https://example.com/products/sonicare_toothbrush_front.jpg",
        asset_id: "asset_45_1",
      },
      {
        type: "image",
        source: "https://example.com/products/sonicare_toothbrush_back.jpg",
        asset_id: "asset_45_2",
      },
    ],
    category_id: "cat_5",
  },
  {
    id: "prod_46",
    product_id: "prod_46",
    name: "Beurer Infrared Heat Lamp",
    product_name: "Beurer Infrared Heat Lamp",
    sku: "BEURERHEATLAMP",
    permalink: "beurer-infrared-heat-lamp",
    quantity: 55,
    price: {
      raw: 45,
      formatted: "45.00",
      formatted_with_symbol: "$45.00",
      formatted_with_code: "45.00 USD",
    },
    line_total: {
      raw: 45,
      formatted: "45.00",
      formatted_with_symbol: "$45.00",
      formatted_with_code: "45.00 USD",
    },
    is_valid: true,
    product_meta: [],
    selected_options: [],
    variant: {
      id: "var_46",
      sku: "BEURERHEATLAMP_WHITE",
      description: "Beurer Infrared Heat Lamp - White",
      inventory: 45,
      price: {
        raw: 45,
        formatted: "45.00",
        formatted_with_symbol: "$45.00",
        formatted_with_code: "45.00 USD",
      },
      is_valid: true,
      brand: "Beurer",
      color: "White",
    },
    image: [
      {
        type: "image",
        source: "https://example.com/products/beurer_heat_lamp_front.jpg",
        asset_id: "asset_46_1",
      },
      {
        type: "image",
        source: "https://example.com/products/beurer_heat_lamp_back.jpg",
        asset_id: "asset_46_2",
      },
    ],
    category_id: "cat_5",
  },
  {
    id: "prod_47",
    product_id: "prod_47",
    name: "Omron TENS Therapy Pain Relief Device",
    product_name: "Omron TENS Therapy Pain Relief Device",
    sku: "OMRONTENS",
    permalink: "omron-tens-therapy-pain-relief-device",
    quantity: 50,
    price: {
      raw: 89,
      formatted: "89.00",
      formatted_with_symbol: "$89.00",
      formatted_with_code: "89.00 USD",
    },
    line_total: {
      raw: 89,
      formatted: "89.00",
      formatted_with_symbol: "$89.00",
      formatted_with_code: "89.00 USD",
    },
    is_valid: true,
    product_meta: [],
    selected_options: [],
    variant: {
      id: "var_47",
      sku: "OMRONTENS_BLACK",
      description: "Omron TENS Therapy Device - Black",
      inventory: 40,
      price: {
        raw: 89,
        formatted: "89.00",
        formatted_with_symbol: "$89.00",
        formatted_with_code: "89.00 USD",
      },
      is_valid: true,
      brand: "Omron",
      color: "Black",
    },
    image: [
      {
        type: "image",
        source: "https://example.com/products/omron_tens_front.jpg",
        asset_id: "asset_47_1",
      },
      {
        type: "image",
        source: "https://example.com/products/omron_tens_back.jpg",
        asset_id: "asset_47_2",
      },
    ],
    category_id: "cat_5",
  },
  {
    id: "prod_48",
    product_id: "prod_48",
    name: "Nature Made Vitamin D3 5000 IU Softgels",
    product_name: "Nature Made Vitamin D3 5000 IU Softgels",
    sku: "NATMADEVITD3",
    permalink: "nature-made-vitamin-d3-5000-iu-softgels",
    quantity: 150,
    price: {
      raw: 12,
      formatted: "12.00",
      formatted_with_symbol: "$12.00",
      formatted_with_code: "12.00 USD",
    },
    line_total: {
      raw: 12,
      formatted: "12.00",
      formatted_with_symbol: "$12.00",
      formatted_with_code: "12.00 USD",
    },
    is_valid: true,
    product_meta: [],
    selected_options: [],
    variant: {
      id: "var_48",
      sku: "NATMADEVITD3_YELLOW",
      description: "Nature Made Vitamin D3 5000 IU - Yellow",
      inventory: 130,
      price: {
        raw: 12,
        formatted: "12.00",
        formatted_with_symbol: "$12.00",
        formatted_with_code: "12.00 USD",
      },
      is_valid: true,
      brand: "Nature Made",
      color: "Yellow",
    },
    image: [
      {
        type: "image",
        source: "https://example.com/products/nature_made_vitamin_d3_front.jpg",
        asset_id: "asset_48_1",
      },
      {
        type: "image",
        source: "https://example.com/products/nature_made_vitamin_d3_back.jpg",
        asset_id: "asset_48_2",
      },
    ],
    category_id: "cat_5",
  },
  {
    id: "prod_49",
    product_id: "prod_49",
    name: "Purell Advanced Hand Sanitizer",
    product_name: "Purell Advanced Hand Sanitizer",
    sku: "PURELLSANITIZER",
    permalink: "purell-advanced-hand-sanitizer",
    quantity: 200,
    price: {
      raw: 5,
      formatted: "5.00",
      formatted_with_symbol: "$5.00",
      formatted_with_code: "5.00 USD",
    },
    line_total: {
      raw: 5,
      formatted: "5.00",
      formatted_with_symbol: "$5.00",
      formatted_with_code: "5.00 USD",
    },
    is_valid: true,
    product_meta: [],
    selected_options: [],
    variant: {
      id: "var_49",
      sku: "PURELLSANITIZER_CLEAR",
      description: "Purell Advanced Hand Sanitizer - Clear",
      inventory: 180,
      price: {
        raw: 5,
        formatted: "5.00",
        formatted_with_symbol: "$5.00",
        formatted_with_code: "5.00 USD",
      },
      is_valid: true,
      brand: "Purell",
      color: "Clear",
    },
    image: [
      {
        type: "image",
        source: "https://example.com/products/purell_hand_sanitizer_front.jpg",
        asset_id: "asset_49_1",
      },
      {
        type: "image",
        source: "https://example.com/products/purell_hand_sanitizer_back.jpg",
        asset_id: "asset_49_2",
      },
    ],
    category_id: "cat_5",
  },
  {
    id: "prod_50",
    product_id: "prod_50",
    name: "DeWalt 20V MAX Cordless Drill",
    product_name: "DeWalt 20V MAX Cordless Drill",
    sku: "DEWALTDRILL",
    permalink: "dewalt-20v-max-cordless-drill",
    quantity: 100,
    price: {
      raw: 129,
      formatted: "129.00",
      formatted_with_symbol: "$129.00",
      formatted_with_code: "129.00 USD",
    },
    line_total: {
      raw: 129,
      formatted: "129.00",
      formatted_with_symbol: "$129.00",
      formatted_with_code: "129.00 USD",
    },
    is_valid: true,
    product_meta: [],
    selected_options: [],
    variant: {
      id: "var_50",
      sku: "DEWALTDRILL_YELLOW",
      description: "DeWalt 20V MAX Cordless Drill - Yellow",
      inventory: 80,
      price: {
        raw: 129,
        formatted: "129.00",
        formatted_with_symbol: "$129.00",
        formatted_with_code: "129.00 USD",
      },
      is_valid: true,
      brand: "DeWalt",
      color: "Yellow",
    },
    image: [
      {
        type: "image",
        source: "https://example.com/products/dewalt_drill_front.jpg",
        asset_id: "asset_50_1",
      },
      {
        type: "image",
        source: "https://example.com/products/dewalt_drill_back.jpg",
        asset_id: "asset_50_2",
      },
    ],
    category_id: "cat_6",
  },
  {
    id: "prod_51",
    product_id: "prod_51",
    name: "Bosch Professional Laser Measure",
    product_name: "Bosch Professional Laser Measure",
    sku: "BOSCHLASER",
    permalink: "bosch-professional-laser-measure",
    quantity: 120,
    price: {
      raw: 99,
      formatted: "99.00",
      formatted_with_symbol: "$99.00",
      formatted_with_code: "99.00 USD",
    },
    line_total: {
      raw: 99,
      formatted: "99.00",
      formatted_with_symbol: "$99.00",
      formatted_with_code: "99.00 USD",
    },
    is_valid: true,
    product_meta: [],
    selected_options: [],
    variant: {
      id: "var_51",
      sku: "BOSCHLASER_BLUE",
      description: "Bosch Professional Laser Measure - Blue",
      inventory: 100,
      price: {
        raw: 99,
        formatted: "99.00",
        formatted_with_symbol: "$99.00",
        formatted_with_code: "99.00 USD",
      },
      is_valid: true,
      brand: "Bosch",
      color: "Blue",
    },
    image: [
      {
        type: "image",
        source: "https://example.com/products/bosch_laser_front.jpg",
        asset_id: "asset_51_1",
      },
      {
        type: "image",
        source: "https://example.com/products/bosch_laser_back.jpg",
        asset_id: "asset_51_2",
      },
    ],
    category_id: "cat_6",
  },
  {
    id: "prod_52",
    product_id: "prod_52",
    name: "Makita Cordless Angle Grinder",
    product_name: "Makita Cordless Angle Grinder",
    sku: "MAKITAANGLEGRINDER",
    permalink: "makita-cordless-angle-grinder",
    quantity: 85,
    price: {
      raw: 149,
      formatted: "149.00",
      formatted_with_symbol: "$149.00",
      formatted_with_code: "149.00 USD",
    },
    line_total: {
      raw: 149,
      formatted: "149.00",
      formatted_with_symbol: "$149.00",
      formatted_with_code: "149.00 USD",
    },
    is_valid: true,
    product_meta: [],
    selected_options: [],
    variant: {
      id: "var_52",
      sku: "MAKITAANGLEGRINDER_BLUE",
      description: "Makita Cordless Angle Grinder - Blue",
      inventory: 70,
      price: {
        raw: 149,
        formatted: "149.00",
        formatted_with_symbol: "$149.00",
        formatted_with_code: "149.00 USD",
      },
      is_valid: true,
      brand: "Makita",
      color: "Blue",
    },
    image: [
      {
        type: "image",
        source: "https://example.com/products/makita_angle_grinder_front.jpg",
        asset_id: "asset_52_1",
      },
      {
        type: "image",
        source: "https://example.com/products/makita_angle_grinder_back.jpg",
        asset_id: "asset_52_2",
      },
    ],
    category_id: "cat_6",
  },
  {
    id: "prod_53",
    product_id: "prod_53",
    name: "Stanley 65-Piece Homeowner's Tool Kit",
    product_name: "Stanley 65-Piece Homeowner's Tool Kit",
    sku: "STANLEYTOOLKIT",
    permalink: "stanley-65-piece-homeowners-tool-kit",
    quantity: 150,
    price: {
      raw: 59,
      formatted: "59.00",
      formatted_with_symbol: "$59.00",
      formatted_with_code: "59.00 USD",
    },
    line_total: {
      raw: 59,
      formatted: "59.00",
      formatted_with_symbol: "$59.00",
      formatted_with_code: "59.00 USD",
    },
    is_valid: true,
    product_meta: [],
    selected_options: [],
    variant: {
      id: "var_53",
      sku: "STANLEYTOOLKIT_YELLOW",
      description: "Stanley 65-Piece Homeowner's Tool Kit - Yellow",
      inventory: 120,
      price: {
        raw: 59,
        formatted: "59.00",
        formatted_with_symbol: "$59.00",
        formatted_with_code: "59.00 USD",
      },
      is_valid: true,
      brand: "Stanley",
      color: "Yellow",
    },
    image: [
      {
        type: "image",
        source: "https://example.com/products/stanley_tool_kit_front.jpg",
        asset_id: "asset_53_1",
      },
      {
        type: "image",
        source: "https://example.com/products/stanley_tool_kit_back.jpg",
        asset_id: "asset_53_2",
      },
    ],
    category_id: "cat_6",
  },
  {
    id: "prod_54",
    product_id: "prod_54",
    name: "Black+Decker Corded Electric Hedge Trimmer",
    product_name: "Black+Decker Corded Electric Hedge Trimmer",
    sku: "BLACKDECKERHEDGE",
    permalink: "black-decker-corded-electric-hedge-trimmer",
    quantity: 60,
    price: {
      raw: 79,
      formatted: "79.00",
      formatted_with_symbol: "$79.00",
      formatted_with_code: "79.00 USD",
    },
    line_total: {
      raw: 79,
      formatted: "79.00",
      formatted_with_symbol: "$79.00",
      formatted_with_code: "79.00 USD",
    },
    is_valid: true,
    product_meta: [],
    selected_options: [],
    variant: {
      id: "var_54",
      sku: "BLACKDECKERHEDGE_ORANGE",
      description: "Black+Decker Corded Electric Hedge Trimmer - Orange",
      inventory: 50,
      price: {
        raw: 79,
        formatted: "79.00",
        formatted_with_symbol: "$79.00",
        formatted_with_code: "79.00 USD",
      },
      is_valid: true,
      brand: "Black+Decker",
      color: "Orange",
    },
    image: [
      {
        type: "image",
        source:
          "https://example.com/products/blackdecker_hedge_trimmer_front.jpg",
        asset_id: "asset_54_1",
      },
      {
        type: "image",
        source:
          "https://example.com/products/blackdecker_hedge_trimmer_back.jpg",
        asset_id: "asset_54_2",
      },
    ],
    category_id: "cat_6",
  },
  {
    id: "prod_55",
    product_id: "prod_55",
    name: "Milwaukee M18 FUEL Cordless Impact Wrench",
    product_name: "Milwaukee M18 FUEL Cordless Impact Wrench",
    sku: "MILWAUKEEWRENCH",
    permalink: "milwaukee-m18-fuel-cordless-impact-wrench",
    quantity: 70,
    price: {
      raw: 249,
      formatted: "249.00",
      formatted_with_symbol: "$249.00",
      formatted_with_code: "249.00 USD",
    },
    line_total: {
      raw: 249,
      formatted: "249.00",
      formatted_with_symbol: "$249.00",
      formatted_with_code: "249.00 USD",
    },
    is_valid: true,
    product_meta: [],
    selected_options: [],
    variant: {
      id: "var_55",
      sku: "MILWAUKEEWRENCH_RED",
      description: "Milwaukee M18 FUEL Impact Wrench - Red",
      inventory: 60,
      price: {
        raw: 249,
        formatted: "249.00",
        formatted_with_symbol: "$249.00",
        formatted_with_code: "249.00 USD",
      },
      is_valid: true,
      brand: "Milwaukee",
      color: "Red",
    },
    image: [
      {
        type: "image",
        source: "https://example.com/products/milwaukee_wrench_front.jpg",
        asset_id: "asset_55_1",
      },
      {
        type: "image",
        source: "https://example.com/products/milwaukee_wrench_back.jpg",
        asset_id: "asset_55_2",
      },
    ],
    category_id: "cat_6",
  },
  {
    id: "prod_56",
    product_id: "prod_56",
    name: "Ryobi 18V Cordless String Trimmer",
    product_name: "Ryobi 18V Cordless String Trimmer",
    sku: "RYOBITRIMMER",
    permalink: "ryobi-18v-cordless-string-trimmer",
    quantity: 90,
    price: {
      raw: 129,
      formatted: "129.00",
      formatted_with_symbol: "$129.00",
      formatted_with_code: "129.00 USD",
    },
    line_total: {
      raw: 129,
      formatted: "129.00",
      formatted_with_symbol: "$129.00",
      formatted_with_code: "129.00 USD",
    },
    is_valid: true,
    product_meta: [],
    selected_options: [],
    variant: {
      id: "var_56",
      sku: "RYOBITRIMMER_GREEN",
      description: "Ryobi 18V Cordless String Trimmer - Green",
      inventory: 70,
      price: {
        raw: 129,
        formatted: "129.00",
        formatted_with_symbol: "$129.00",
        formatted_with_code: "129.00 USD",
      },
      is_valid: true,
      brand: "Ryobi",
      color: "Green",
    },
    image: [
      {
        type: "image",
        source: "https://example.com/products/ryobi_trimmer_front.jpg",
        asset_id: "asset_56_1",
      },
      {
        type: "image",
        source: "https://example.com/products/ryobi_trimmer_back.jpg",
        asset_id: "asset_56_2",
      },
    ],
    category_id: "cat_6",
  },
  {
    id: "prod_57",
    product_id: "prod_57",
    name: "Craftsman Mechanics Tool Set, 230-Piece",
    product_name: "Craftsman Mechanics Tool Set, 230-Piece",
    sku: "CRAFTSMANSET",
    permalink: "craftsman-mechanics-tool-set-230-piece",
    quantity: 110,
    price: {
      raw: 149,
      formatted: "149.00",
      formatted_with_symbol: "$149.00",
      formatted_with_code: "149.00 USD",
    },
    line_total: {
      raw: 149,
      formatted: "149.00",
      formatted_with_symbol: "$149.00",
      formatted_with_code: "149.00 USD",
    },
    is_valid: true,
    product_meta: [],
    selected_options: [],
    variant: {
      id: "var_57",
      sku: "CRAFTSMANSET_RED",
      description: "Craftsman 230-Piece Mechanics Tool Set - Red",
      inventory: 90,
      price: {
        raw: 149,
        formatted: "149.00",
        formatted_with_symbol: "$149.00",
        formatted_with_code: "149.00 USD",
      },
      is_valid: true,
      brand: "Craftsman",
      color: "Red",
    },
    image: [
      {
        type: "image",
        source: "https://example.com/products/craftsman_tool_set_front.jpg",
        asset_id: "asset_57_1",
      },
      {
        type: "image",
        source: "https://example.com/products/craftsman_tool_set_back.jpg",
        asset_id: "asset_57_2",
      },
    ],
    category_id: "cat_6",
  },
  {
    id: "prod_58",
    product_id: "prod_58",
    name: "Klein Tools Non-Contact Voltage Tester",
    product_name: "Klein Tools Non-Contact Voltage Tester",
    sku: "KLEINVOLTAGETESTER",
    permalink: "klein-tools-non-contact-voltage-tester",
    quantity: 140,
    price: {
      raw: 29,
      formatted: "29.00",
      formatted_with_symbol: "$29.00",
      formatted_with_code: "29.00 USD",
    },
    line_total: {
      raw: 29,
      formatted: "29.00",
      formatted_with_symbol: "$29.00",
      formatted_with_code: "29.00 USD",
    },
    is_valid: true,
    product_meta: [],
    selected_options: [],
    variant: {
      id: "var_58",
      sku: "KLEINVOLTAGETESTER_YELLOW",
      description: "Klein Tools Non-Contact Voltage Tester - Yellow",
      inventory: 120,
      price: {
        raw: 29,
        formatted: "29.00",
        formatted_with_symbol: "$29.00",
        formatted_with_code: "29.00 USD",
      },
      is_valid: true,
      brand: "Klein Tools",
      color: "Yellow",
    },
    image: [
      {
        type: "image",
        source: "https://example.com/products/klein_voltage_tester_front.jpg",
        asset_id: "asset_58_1",
      },
      {
        type: "image",
        source: "https://example.com/products/klein_voltage_tester_back.jpg",
        asset_id: "asset_58_2",
      },
    ],
    category_id: "cat_6",
  },
  {
    id: "prod_59",
    product_id: "prod_59",
    name: "Dremel 4000 High Performance Rotary Tool Kit",
    product_name: "Dremel 4000 High Performance Rotary Tool Kit",
    sku: "DREMEL4000",
    permalink: "dremel-4000-rotary-tool-kit",
    quantity: 130,
    price: {
      raw: 89,
      formatted: "89.00",
      formatted_with_symbol: "$89.00",
      formatted_with_code: "89.00 USD",
    },
    line_total: {
      raw: 89,
      formatted: "89.00",
      formatted_with_symbol: "$89.00",
      formatted_with_code: "89.00 USD",
    },
    is_valid: true,
    product_meta: [],
    selected_options: [],
    variant: {
      id: "var_59",
      sku: "DREMEL4000_BLACK",
      description: "Dremel 4000 High Performance Rotary Tool Kit - Black",
      inventory: 100,
      price: {
        raw: 89,
        formatted: "89.00",
        formatted_with_symbol: "$89.00",
        formatted_with_code: "89.00 USD",
      },
      is_valid: true,
      brand: "Dremel",
      color: "Black",
    },
    image: [
      {
        type: "image",
        source: "https://example.com/products/dremel_4000_front.jpg",
        asset_id: "asset_59_1",
      },
      {
        type: "image",
        source: "https://example.com/products/dremel_4000_back.jpg",
        asset_id: "asset_59_2",
      },
    ],
    category_id: "cat_6",
  },
  {
    id: "prod_60",
    product_id: "prod_60",
    name: "Hitachi C10FCG 10-Inch Compound Miter Saw",
    product_name: "Hitachi C10FCG 10-Inch Compound Miter Saw",
    sku: "HITACHIMITERSAW",
    permalink: "hitachi-c10fcg-compound-miter-saw",
    quantity: 50,
    price: {
      raw: 179,
      formatted: "179.00",
      formatted_with_symbol: "$179.00",
      formatted_with_code: "179.00 USD",
    },
    line_total: {
      raw: 179,
      formatted: "179.00",
      formatted_with_symbol: "$179.00",
      formatted_with_code: "179.00 USD",
    },
    is_valid: true,
    product_meta: [],
    selected_options: [],
    variant: {
      id: "var_60",
      sku: "HITACHIMITERSAW_GREEN",
      description: "Hitachi C10FCG Compound Miter Saw - Green",
      inventory: 40,
      price: {
        raw: 179,
        formatted: "179.00",
        formatted_with_symbol: "$179.00",
        formatted_with_code: "179.00 USD",
      },
      is_valid: true,
      brand: "Hitachi",
      color: "Green",
    },
    image: [
      {
        type: "image",
        source: "https://example.com/products/hitachi_miter_saw_front.jpg",
        asset_id: "asset_60_1",
      },
      {
        type: "image",
        source: "https://example.com/products/hitachi_miter_saw_back.jpg",
        asset_id: "asset_60_2",
      },
    ],
    category_id: "cat_6",
  },
];

export const carts = [
  {
    id: "cart_35846",
    created: 1696103940,
    updated: 1696449540,
    expires: 1697659140,
    total_items: 7,
    total_unique_items: 5,
    subtotal: {
      raw: 243.23,
      formatted: "243.23",
      formatted_with_symbol: "$243.23",
      formatted_with_code: "USD 243.23",
    },
    hosted_checkout_url: "https://checkout.example.com/5744",
    line_items: [],
    currency: {
      code: "USD",
      symbol: "$",
    },
    discount: [],
    meta: null,
  },
  {
    id: "cart_35847",
    created: 1696103940,
    updated: 1696449540,
    expires: 1697659140,
    total_items: 7,
    total_unique_items: 5,
    subtotal: {
      raw: 243.23,
      formatted: "243.23",
      formatted_with_symbol: "$243.23",
      formatted_with_code: "USD 243.23",
    },
    hosted_checkout_url: "https://checkout.example.com/5744",
    line_items: [],
    currency: {
      code: "USD",
      symbol: "$",
    },
    discount: [],
    meta: null,
  },
];
